### ISSUE TITLE
Handling different dotnet version

### ISSUE THREAD

**Issue by jmauro** [chef-cookbooks/ms_dotnet4#3]
Hi,
Since different dotnet version are avalaible different cookbook has been created, I tried to merge all the "ms_dotnetX" cookbook into one (This would be easier for powershell cookbook and its dependency), I would be glad to have your input since I took the code from your cookbook ms_dotnet4: [Criteo Github](https://github.com/criteo-cookbooks/ms_dotnet)
Any comments or PR would be appreciated.

Regards,
JM

**Comment by csharris** [comment]
Not sure if it matters, but I did this as well for the exact same reason. I think that this would be a common scenario for people using these cookbooks.

**Comment by jmauro** [comment]
Feel free to submit any comment or enhancement.

Regards,
JM

**Comment by tas50** [comment]
@jmauro Thanks for creating that. It's certainly simpler if you need more than one version instlaled.
